const menuCategories = [
	{
		id: 1,
		name: 'Vegetables',
		items: [
			{ id: 1, name: 'broccoli' },
			{ id: 2, name: 'carrot' },
			{ id: 3, name: 'asparagus' },
			{ id: 4, name: 'cauliflower' },
			{ id: 5, name: 'corn' },
			{ id: 6, name: 'cucumber' },
			{ id: 7, name: 'green pepper' },
			{ id: 8, name: 'lettuce' },
			{ id: 9, name: 'mushrooms' },
			{ id: 10, name: 'onion' },
			{ id: 11, name: 'potato' },
			{ id: 12, name: 'pumpkin' },
			{ id: 13, name: 'red pepper' },
			{ id: 14, name: 'tomato' },
			{ id: 15, name: 'beetroot' },
			{ id: 16, name: 'brussel sprouts' },
			{ id: 17, name: 'peas' },
			{ id: 18, name: 'zucchini' },
			{ id: 19, name: 'radish' },
			{ id: 20, name: 'sweet potato' },
			{ id: 21, name: 'artichoke' },
			{ id: 22, name: 'leek' },
			{ id: 23, name: 'cabbage' },
			{ id: 24, name: 'celery' },
			{ id: 25, name: 'chili' },
			{ id: 26, name: 'garlic' },
			{ id: 27, name: 'basil' },
			{ id: 28, name: 'coriander' },
			{ id: 29, name: 'parsley' },
			{ id: 30, name: 'dill' },
			{ id: 31, name: 'rosemary' },
			{ id: 32, name: 'oregano' },
			{ id: 33, name: 'cinnamon' },
			{ id: 34, name: 'saffron' },
			{ id: 35, name: 'green bean' },
			{ id: 36, name: 'bean' },
			{ id: 37, name: 'chickpea' },
			{ id: 38, name: 'lentil' },
		],
	},
	{
		id: 2,
		name: 'Fruits',
		items: [
			{ id: 1, name: 'apple' },
			{ id: 2, name: 'apricot' },
			{ id: 3, name: 'avocado' },
			{ id: 4, name: 'banana' },
			{ id: 5, name: 'blackberry' },
			{ id: 6, name: 'blackcurrant' },
			{ id: 7, name: 'blueberry' },
			{ id: 8, name: 'boysenberry' },
			{ id: 9, name: 'cherry' },
			{ id: 10, name: 'coconut' },
			{ id: 11, name: 'fig' },
			{ id: 12, name: 'grape' },
			{ id: 13, name: 'grapefruit' },
			{ id: 14, name: 'kiwifruit' },
			{ id: 15, name: 'lemon' },
			{ id: 16, name: 'lime' },
			{ id: 17, name: 'lychee' },
			{ id: 18, name: 'mandarin' },
			{ id: 19, name: 'mango' },
			{ id: 20, name: 'melon' },
			{ id: 21, name: 'nectarine' },
			{ id: 22, name: 'orange' },
			{ id: 23, name: 'papaya' },
			{ id: 24, name: 'passion fruit' },
			{ id: 25, name: 'peach' },
			{ id: 26, name: 'pear' },
			{ id: 27, name: 'pineapple' },
			{ id: 28, name: 'plum' },
			{ id: 29, name: 'pomegranate' },
			{ id: 30, name: 'quince' },
			{ id: 31, name: 'raspberry' },
			{ id: 32, name: 'strawberry' },
			{ id: 33, name: 'watermelon' },
		],
	},
	{
		id: 3,
		name: 'Dishes',
		items: [
			{ id: 1, name: 'salad' },
			{ id: 2, name: 'pizza' },
			{ id: 3, name: 'pasta' },
			{ id: 4, name: 'popcorn' },
			{ id: 5, name: 'lobster' },
			{ id: 6, name: 'steak' },
			{ id: 7, name: 'bbq' },
			{ id: 8, name: 'pudding' },
			{ id: 9, name: 'hamburger' },
			{ id: 10, name: 'pie' },
			{ id: 11, name: 'cake' },
			{ id: 12, name: 'sausage' },
			{ id: 13, name: 'tacos' },
			{ id: 14, name: 'kebab' },
			{ id: 15, name: 'poutine' },
			{ id: 16, name: 'seafood' },
			{ id: 17, name: 'chips' },
			{ id: 18, name: 'fries' },
			{ id: 19, name: 'masala' },
			{ id: 20, name: 'paella' },
			{ id: 21, name: 'som tam' },
			{ id: 22, name: 'chicken' },
			{ id: 23, name: 'toast' },
			{ id: 24, name: 'marzipan' },
			{ id: 25, name: 'tofu' },
			{ id: 26, name: 'ketchup' },
			{ id: 27, name: 'hummus' },
			{ id: 28, name: 'chili' },
			{ id: 29, name: 'maple syrup' },
			{ id: 30, name: 'parma ham' },
			{ id: 31, name: 'fajitas' },
			{ id: 32, name: 'champ' },
			{ id: 33, name: 'lasagna' },
			{ id: 34, name: 'poke' },
			{ id: 35, name: 'chocolate' },
			{ id: 36, name: 'croissant' },
			{ id: 37, name: 'arepas' },
			{ id: 38, name: 'bunny chow' },
			{ id: 39, name: 'pierogi' },
			{ id: 40, name: 'donuts' },
			{ id: 41, name: 'rendang' },
			{ id: 42, name: 'sushi' },
			{ id: 43, name: 'ice cream' },
			{ id: 44, name: 'duck' },
			{ id: 45, name: 'curry' },
			{ id: 46, name: 'beef' },
			{ id: 47, name: 'goat' },
			{ id: 48, name: 'lamb' },
			{ id: 49, name: 'turkey' },
			{ id: 50, name: 'pork' },
			{ id: 51, name: 'fish' },
			{ id: 52, name: 'crab' },
			{ id: 53, name: 'bacon' },
			{ id: 54, name: 'ham' },
			{ id: 55, name: 'pepperoni' },
			{ id: 56, name: 'salami' },
			{ id: 57, name: 'ribs' },
		],
	},
];

export default menuCategories;
